# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'e4c86c21-8b2f-4dce-a923-a178ce6fff8b'

  # Function app name
  functionAppName: ''

  # Agent VM image name
  vmImageName: 'windows-2019'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/src/core/LearnDevOps.Automation.Functions'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - template: jobs-build.yml


 
